apiVersion: "v1"
kind: "Pod"
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: maven
      image: 'sunshowercloud/sunshower-base:latest'
      command:
        - cat
      tty: true

